services:
  baseball-api:
    build:
      context: BaseballApi
    restart: unless-stopped
    image: baseball-api
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build:
      context: baseball-app
    restart: always
    image: eschenfeldt/baseball-app
    depends_on:
      - baseball-api

  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - baseball-api
      - app
    image: baseball-gateway
