services:
    baseball-api:
        build:
            context: BaseballApi
        restart: always
        image: baseball-api
        extra_hosts:
            - "host.docker.internal:host-gateway"

    app:
        build:
            context: baseball-app
        restart: always
        image: eschenfeldt/baseball-app
        depends_on:
            - baseball-api

    proxy:
        build: proxy
        restart: always
        ports:
            - 80:80
            - 443:443
        depends_on:
            - baseball-api
            - app
        image: baseball-gateway
        volumes:
            - certbot-etc:/etc/letsencrypt:ro
            - certbot-var:/var/lib/letsencrypt:ro
            - web-root:/var/www/html:ro
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        container_name: certbot
        volumes:
            - certbot-etc:/etc/letsencrypt:rw
            - certbot-var:/var/lib/letsencrypt:rw
            - web-root:/var/www/html:rw
        depends_on:
            - proxy
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
    certbot-etc:
    certbot-var:
    web-root:
