services:
    baseball-api:
        build:
            context: BaseballApi
        restart: always
        image: baseball-api
        extra_hosts:
            - "host.docker.internal:host-gateway"

    tests:
      build:
        context: BaseballApiTests
      restart: always
      image: baseball-api-tests
      depends_on:
        - baseball-api
    
